language: php

php:
  - 8.0
  - 8.1
  - 8.2
  - 8.3

before_install:
  - composer self-update
  - composer clear-cache

install: composer update --no-interaction --no-ansi --no-progress --no-suggest

script: ./vendor/bin/phpunit --coverage-text
